services:
  - type: web
    name: task-management-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        value: postgresql://username:password@host:5432/database_name
      - key: DATABASE_USERNAME
        value: your_db_username
      - key: DATABASE_PASSWORD
        value: your_db_password
